name: "01-EKS"
on:
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC token generation
  contents: read

jobs:
  Plan:
    uses: subani-in/EKS-ELK-Terraform-v1/.github/workflows/aws_tf_plan.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Apply:
    needs: Plan

    uses: subani-in/EKS-ELK-Terraform-v1/.github/workflows/aws_tf_appy.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}
